# Generated by Django 4.2 on 2024-06-04 06:43

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import pgvector.django


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('messages', models.JSONField()),
                ('files', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='none'), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='files',
            fields=[
                ('filename', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='filecontent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk', models.CharField(max_length=3700)),
                ('feature_vector', pgvector.django.VectorField(dimensions=1536)),
                ('filename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.files')),
            ],
        ),
    ]
