# Generated by Django 4.2 on 2024-06-04 07:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_chat_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, null=True), size=None),
        ),
    ]
