# Generated by Django 4.2 on 2024-06-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_excelfilecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='function',
            field=models.CharField(default='norm', max_length=255),
            preserve_default=False,
        ),
    ]
