# Generated by Django 4.2 on 2024-06-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_chat_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='function',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
