# Generated by Django 4.2 on 2024-07-29 05:40

from django.db import migrations, models
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_chat_function'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tvsm_Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('vehicle_fuel_type', models.CharField(max_length=100)),
                ('vehicle_prime_users', models.CharField(max_length=1000)),
                ('vehicle_mileage', models.IntegerField()),
                ('vehicle_price', models.IntegerField()),
                ('vehicle_daily_commute', models.CharField(max_length=1000)),
                ('vehicle_description', models.CharField(max_length=2000)),
                ('feature_vector', pgvector.django.VectorField(dimensions=1536)),
            ],
        ),
    ]
