# Generated by Django 4.2 on 2024-07-30 11:39

from django.db import migrations, models
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_tvsm_vehicles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tvsm_Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('vehicle_name', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
                ('product_primary_color', models.CharField(max_length=100)),
                ('product_accent_color', models.CharField(max_length=100)),
                ('product_description', models.CharField(max_length=100)),
                ('product_user', models.CharField(max_length=100)),
                ('feature_vector', pgvector.django.VectorField(dimensions=1536)),
            ],
        ),
        migrations.AddField(
            model_name='tvsm_vehicles',
            name='vehical_img_link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tvsm_vehicles',
            name='vehical_link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tvsm_vehicles',
            name='vehical_testdrive_link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
