# Generated by Django 4.2 on 2024-07-31 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_tvsm_accessories_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvsm_accessories',
            name='product_description',
            field=models.CharField(max_length=1500),
        ),
    ]
