# Generated by Django 4.2 on 2024-08-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_tvsm_accessories_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvsm_vehicles',
            name='vehical_booking_link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
