# Generated by Django 4.2 on 2024-08-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_tvsm_accessories_product_img_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='messagestoshow',
            field=models.JSONField(null=True),
        ),
    ]
