# Generated by Django 4.2 on 2024-08-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_chat_messagestoshow'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvsm_vehicles',
            name='vehical_img_link_2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
